# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lipsync4urlife CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - env:
          CI: true
          GENIUS_CLIENT_KEY: ${{ secrets.GENIUS_CLIENT_KEY }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
    - run: npm test
    
  docker-ci:
    needs: build
    runs-on: ubuntu-latest

    steps:         
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          secrets: |
            "GENIUS_CLIENT_KEY=${{ secrets.GENIUS_CLIENT_KEY }}"
            "RAPID_API_KEY=${{ secrets.RAPID_API_KEY }}"
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lipsync4urlife:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - uses: actions/checkout@v2
